# Generated by Django 5.2 on 2025-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerslikes',
            name='pos',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='questionslikes',
            name='pos',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='answerslikes',
            unique_together={('profile', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionslikes',
            unique_together={('profile', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionstags',
            unique_together={('question', 'tag')},
        ),
    ]
