# Generated by Django 4.2.20 on 2025-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answerslikes_pos_questionslikes_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='answerslikes',
            name='pos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questionslikes',
            name='pos',
            field=models.BooleanField(default=0),
        ),
    ]
