upstream ruquest {
	server 127.0.0.1:8000;
}

server {
	listen 80 default_server;
	server_name ruquest.ru;

	autoindex off;

	error_log /var/log/nginx/ruquest_error.log;
	access_log /var/log/nginx/ruquest_access.log;

	location /static/img/ {
		alias /home/kirill/files/PythonProjects/VkWeb2025_DZ2/static/img/;
		expires 30s;
	}

	location ~* \.(js|css|jpg|png|jpeg|webp)$ {
		root /home/kirill/files/PythonProjects/VkWeb2025_DZ2/;
		expires 30s;
	}

	location / {
		proxy_pass http://ruquest;
		proxy_set_header Host $host;
		proxy_cache ruquest_zone;
		proxy_cache_valid 200 302 10m;

		add_header X-Cache-Status $upstream_cache_status;

		proxy_cache_bypass $http_pragma $http_cache_control;
		proxy_no_cache $http_pragma $http_cache_control;

		proxy_cache_key "$scheme$host$request_uri";

		proxy_ignore_headers Set-Cookie;
		proxy_hide_header Set-Cookie;
	}

}
